apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-shipedge-app
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-shipedge
  template:
    metadata:
      labels:
        app: hello-world-shipedge
    spec:
      imagePullSecrets:
        - name: i1pro-key
      containers:
        - name: app
          image: i1pro/hello-world-app:latest
          ports:
            - containerPort: 3000

