apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-service
  namespace: jenkins
spec:
  selector:
    app: jenkins-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer